# Application Name
spring.application.name=interview-question-bank

  # ===============================
  # DATABASE CONFIGURATION
  # ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres}
spring.datasource.username=${DB_USERNAME:postgres.oryshinfkqticdhvrntg}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

  # ===============================
  # APP CONFIG
  # ===============================

app.similarity-threshold=${SIMILARITY_THRESHOLD:0.82}
app.embedding-dimensions=${EMBEDDING_DIMENSIONS:256}

  # ===============================
  # SWAGGER / OPENAPI
  # ===============================

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
